language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
  - pypy3
before_install:
  - sudo apt-get install libgmp3-dev libmpfr-dev libmpc-dev
  - pip install --use-mirrors cffi
  - pip install --use-mirrors pytest
install:
  - python setup.py install
script:
  - py.test -v
notifications:
    email: false
