language: python
python:
  - 2.6
  - 2.7
  - pypy
before_install:
  - sudo apt-get install libgmp3-dev libmpfr-dev
  - pip install --use-mirrors cffi
  - pip install --use-mirrors pytest
install:
  - python setup.py install
script:
  - py.test
notifications:
    email: false
