language: python
python:
  - 2.6
  - 2.7
  - pypy
matrix:
    allow_failures:
      - python: pypy
before_install:
  - sudo apt-get install libgmp3-dev
  - pip install --use-mirrors pytest
install:
  - python setup.py develop
script:
  - py.test
notifications:
    email: false
